name: SonnyTVo
favicon: null
layout_spectrum: 0.5344487719703466
typography_spectrum: 0.9776180125772953
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5519048406276852
  lightness: 0.9383682617917657
  saturation: 0.6833246010355651
  rhythmicContrast: 0.5013777872081846
purpose: []
